### ISSUE TITLE
Tarantulas don't burn in lava.

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#130] opened 2020-05-28 14:38 UTC
Tarantulas don't take any kind of damage when they are swimming in lava. I think, this wasn't intended.

**Comment by KaylebJay** [comment] 2020-05-28 14:52
That's odd, definitely not intended behaviour.

**Comment by KaylebJay** [comment] 2020-05-28 15:32
A few other mobs had this 'feature'. Fixed in https://github.com/KaylebJay/petz/commit/e64856149a91c9cda57eaa0e2d5862336efaae73

**Closed as completed by KaylebJay** 2020-05-28 15:32 UTC
Labels: Bugz :bug:
